name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev libmpfr-dev libmpc-dev python-dev libgmp3-dev
          sudo apt-get install -y python3.8
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3.8
      - name: Install project dependencies
        run: |
          source $HOME/.poetry/env
          poetry install
      - name: Run pytest
        run: |
          poetry run pytest ./tests