name: test

on: [push, pull_request]

jobs:
  linux_test:
    name: Linux test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev libmpfr-dev libmpc-dev libgmp3-dev python3.8 python3.8-venv python3.8-dev libpython3.8-dev

      - name: Install and set up poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3.8
          source $HOME/.poetry/env
          poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          source $HOME/.poetry/env
          poetry install

      - name: Run lint
        run: |
          source .venv/bin/activate
          make lint

      - name: Run test
        run: |
          source .venv/bin/activate
          make test

      - name: Build distribution
        run: |
          source $HOME/.poetry/env
          poetry build

      - name: Upload distribution
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist